name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: connect to the server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
      - name: pull and restart server
        run: |
          cd toxic-market-place/
          git pull origin main
          pm2 delete index.ts
          pm2 start "npm run start" --name index.ts