name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo 'start code deploy'
            cd toxic-market-place/
            git checkout main
            git pull origin main --no-edit
            npm i
            pm2 delete index.ts
            pm2 start "npm run start" --name index.ts
            echo 'code deploy end'